### ISSUE TITLE
[Bug] Server installation fail

### ISSUE THREAD

**Issue by maxime-boussin** [TeamMoegMC/TheWinterRescue#38]
### Error Behaviour

I tried to install my server as you mention, with your serverstarter, but the "mod" folder stay empty after installation and I got some errors in my log file like that:
```
[10:03:31] [ERROR] Error while trying to get URL from cursemeta for mod ModEntryRaw(projectID=306770, fileID=3459118)

java.io.IOException: Request to https://cursemeta.dries007.net/306770/3459118.json was not successful.
	at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType$downloadMods$1.accept(CursePackType.kt:202)
	at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType$downloadMods$1.accept(CursePackType.kt:26)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```
Maybe I missed something but I don't know what.
I have the same issue on Windows 10 with the .bat and on ubuntu 18.01 with the .sh

### Expected Behaviour

Any solution?

### Reproduce

Install the server as mention

### Modpack version

0.4.7

**Comment by khjxiaogu** [comment]
Curseforge disabled third party mod installer. So it's no longer available and would be removed in next version.
Means you should make server pack on your own
