### ISSUE TITLE
 When I die on my server I will go back to the main menu

### ISSUE THREAD

**Issue by KlNon** [TeamMoegMC/TheWinterRescue#50]
### Error Behaviour

[14:58:33 INFO]: KlNon killed by Zombie
[14:58:53 ERROR]: Exception caught during firing event: null
        Index: 13
        Listeners:
                0: HIGH
                1: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                2: NORMAL
                3: net.minecraftforge.eventbus.EventBus$$Lambda$2593/1559972721@5a61facb
                4: ASM: class net.mehvahdjukaar.supplementaries.events.ServerEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                5: ASM: class com.simibubi.create.content.curiosities.bell.HauntedBellPulser hauntedBellCreatesPulse(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                6: ASM: se.mickelus.tetra.effect.ItemEffectHandler@2a29f080 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                7: ASM: class top.theillusivec4.diet.common.capability.DietCapabilityEventsListener playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                8: ASM: class com.cannolicatfish.rankine.events.RankineEventHandler onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                9: ASM: class com.teammoeg.frostedheart.events.PlayerEvents sendForecastMessages(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                10: ASM: class com.teammoeg.frostedheart.events.CommonEvents tickResearch(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                11: ASM: class com.teammoeg.frostedheart.climate.TemperatureUpdate updateTemperature(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                12: ASM: class com.teammoeg.frostedheart.climate.TemperatureUpdate regulateTemperature(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                13: ASM: class com.teammoeg.frostedheart.research.inspire.EnergyCore tickEnergy(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                14: ASM: class gloridifice.watersource.common.event.CommonEventHandler onPlayerTickEvent(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                15: ASM: flaxbeard.immersivepetroleum.common.CommonEventHandler@b2c44b1 handleBoatImmunity(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                16: ASM: me.lucko.spark.forge.ForgeTickHook@5f7983b3 onTick(Lnet/minecraftforge/event/TickEvent;)V
                17: ASM: me.lucko.spark.forge.ForgeTickReporter@38a8a1f3 onTick(Lnet/minecraftforge/event/TickEvent;)V
                18: LOW
                19: ASM: se.mickelus.tetra.items.forged.VibrationDebuffer@5da157f5 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                20: ASM: se.mickelus.tetra.advancements.BlockLookTrigger@6fd362eb onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                21: ASM: se.mickelus.tetra.items.modular.impl.toolbelt.booster.TickHandlerBooster@6d0a0b2d onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
java.lang.NullPointerException
        at com.teammoeg.frostedheart.research.inspire.EnergyCore.dT(EnergyCore.java:64)
        at com.teammoeg.frostedheart.research.inspire.EnergyCore.tickEnergy(EnergyCore.java:222)
        at net.minecraftforge.eventbus.ASMEventHandler_460_EnergyCore_tickEnergy_PlayerTickEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:304)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:284)
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:83)
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:224)
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:526)
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:298)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:243)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:142)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1113)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:338)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1003)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:818)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
        at java.lang.Thread.run(Thread.java:750)

[14:58:53 FATAL]: Preparing crash report with UUID 0899efa8-f940-4854-832a-bbc4fbb12386
[14:58:53 WARN]: Unable to process packets for [my IP]
net.minecraft.crash.ReportedException: Ticking player
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:605) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:298) ~[?:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:243) ~[?:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:142) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1113) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:338) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1003) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:818) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_342]
Caused by: java.lang.NullPointerException
        at com.teammoeg.frostedheart.research.inspire.EnergyCore.dT(EnergyCore.java:64) ~[frostedheart:1.16.5-0.5.1-hf5]
        at com.teammoeg.frostedheart.research.inspire.EnergyCore.tickEnergy(EnergyCore.java:222) ~[frostedheart:1.16.5-0.5.1-hf5]
        at net.minecraftforge.eventbus.ASMEventHandler_460_EnergyCore_tickEnergy_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:304) ~[mohist-1.16.5-52-server.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:284) ~[mohist-1.16.5-52-server.jar:?]
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:83) ~[forge:?]
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:224) ~[?:?]
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:526) ~[?:?]
        ... 9 more

### Expected Behaviour

normal death

### Reproduce

die in server:
[The-Winter-Rescue-0.5.1-hf5.zip]
All steps are as required. 
: (

### Modpack version

The-Winter-Rescue-0.5.1-hf5

### Server version

mohist-1.16.5-52-server

**Comment by KlNon** [comment]
These server core also make the crash:
mohist-1.16.5-1082-server.jar
arclight-forge-1.16.5-1.0.24.jar

**Comment by khjxiaogu** [comment]
0.5.2-rc1 fixed
